# Generated by Django 3.2.6 on 2021-08-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20210819_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='customer_acc_number',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
