# Generated by Django 3.2.6 on 2021-08-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_auto_20210819_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='id',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer_acc_number',
            field=models.CharField(default='1', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
