# Generated by Django 3.2.6 on 2021-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_auto_20210819_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_to_acc_number', models.CharField(max_length=20)),
                ('customer_from_acc_number', models.CharField(max_length=20)),
                ('transaction_time', models.CharField(max_length=100)),
            ],
        ),
    ]
