# Generated by Django 3.2.6 on 2021-08-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_customertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertransaction',
            name='transaction_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
